### ISSUE TITLE
Issue 5 for preprocessing and data transformation milestone

### ISSUE THREAD

**Issue by Paula-Wang** [Paula-Wang/BI-2-Project-#5]
- [x] Confirmation of the presence of missing values
- [ ] Data imputation (if applicable)
- [x] Data transformation (if applicable)

**Comment by Paula-Wang** [comment]
Data imputation was not applicable with the dataset
