### ISSUE TITLE
Issue 6 for Milestone 3: Training the Model

### ISSUE THREAD

**Issue by Paula-Wang** [Paula-Wang/BI-2-Project-#6]
- [ ] Data splitting
- [ ] Bootstrapping
- [ ] Cross validation (basic, repeated or LOOCV)
- [ ] Model training for either classification, regression, association, or clustering (as applicable)
- [ ] Model performance comparison using resamples (for classification and regression)
